# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/1fdc9458-bd1c-46c0-8364-2b2c7fb9f344";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/201c25ea-ac04-4e4b-bc01-5d7c31fe9b94";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A5D2-E942";
      fsType = "vfat";
    };

  swapDevices = [ ];

  nix.maxJobs = lib.mkDefault 4;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";

  services.xserver.xrandrHeads = [
    {
      output = "DP-1";
      primary = true;
      monitorConfig = ''
      Option "LeftOf" "HDMI-1"
      '';
    }
    {
      output = "HDMI-1";
    }
  ];
}
