xsetroot -cursor_name left_ptr
(xrandr --listproviders | grep --quiet NVIDIA-0) && xrandr –setprovideroutputsource modesetting NVIDIA-0
xrandr --auto
xrdb -merge $HOME/.Xresources
autocutsel -fork &
autocutsel -selection PRIMARY -fork &
eval `dbus-launch --auto-syntax`

# {{{ Log settings
errorlog="$HOME/.xsession-errors"

# Start with a clean log file every time
if ( cp /dev/null "$errorlog" 2> /dev/null ); then
    chmod 600 "$errorlog"
    exec rogryza-xmonad > "$errorlog" 2>&1
fi
# }}}
